- name: Install Hyprland Ecosystem
  community.general.pacman:
    name:
      - starship
      - zsh
      - hyprland
      - kitty
      - firefox
      - xdg-utils
      - waybar
      - npm
      - wofi
      - swww
      - mako
      - grim
      - slurp
      - wl-clipboard
      - pavucontrol
      - nm-connection-editor
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - qt5-wayland
      - qt6-wayland
      - polkit-kde-agent
      - ttf-jetbrains-mono-nerd
      - ttf-font-awesome
    state: present
  become: true

- name: Install Audio Stack (PipeWire)
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - wireplumber
    state: present
  become: true

- name: Set Zsh as the default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
  become: true

- name: Ensure base .config directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
