- name: Install Hyprland Ecosystem
  community.general.pacman:
    name:
      - hyprland
      - kitty
      - firefox
      - xdg-utils
      - waybar
      - rofi-wayland
      - swww
      - mako
      - grim
      - slurp
      - wl-clipboard
      - pavucontrol
      - nm-connection-editor
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - qt5-wayland
      - qt6-wayland
      - polkit-kde-agent
      - ttf-jetbrains-mono-nerd
      - ttf-font-awesome
    state: present

- name: Install Audio Stack (PipeWire)
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - wireplumber
    state: present

- name: Ensure config directories exist
  ansible.builtin.file:
    path: "/home/{{ ansible_facts['user_id'] }}/.config/{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0755'
  loop:
    - hypr
    - kitty
    - waybar
