---
- name: Install GNU Stow
  community.general.pacman:
    name: stow
    state: present

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.dest }}"
    recursive: yes
    update: yes
    accept_hostkey: yes
  become: false

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  become: false

- name: Find all app folders in common and linux subdirs
  ansible.builtin.find:
    paths: "{{ dotfiles.dest }}/{{ item }}"
    file_type: directory
    recurse: no
  loop: "{{ dotfiles.subdirs }}"
  register: found_dotfiles
  become: false

- name: Symlink dotfiles using Stow
  ansible.builtin.shell:
    # -R: Restow (good for updates)
    # -d: The source directory (e.g., ~/.dotfiles/common)
    # -t: The target (your home folder)
    cmd: "stow -R -v -d {{ dotfiles.dest }}/{{ item.0.item }} -t /home/{{ username }} {{ item.1.path | basename }}"
  loop: "{{ found_dotfiles.results | subelements('files', skip_missing=True) }}"
  register: stow_out
  changed_when: "'LINK' in stow_out.stderr or 'UNLINK' in stow_out.stderr"
  failed_when: stow_out.rc != 0
  become: false
